// ACP stdio adapter for Buzz. Inference stays in the existing ChatGPT-backed executor.
import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import readline from 'node:readline';import {randomUUID} from 'node:crypto';import {spawn} from 'node:child_process';
const root=path.dirname(fileURLToPath(import.meta.url)),agentId=process.argv[2]||'general-manager',sessions=new Map();
const tokenFile=process.env.EQUIPE_A2A_TOKEN_FILE||path.join(root,'.runtime/buzz-token'),base=process.env.EQUIPE_A2A_URL||'http://127.0.0.1:4320';
const output=x=>process.stdout.write(JSON.stringify(x)+'\n');
async function call(method,params){const token=fs.readFileSync(tokenFile,'utf8').trim();const response=await fetch(base+'/a2a/'+encodeURIComponent(agentId),{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json','A2A-Version':'1.0'},body:JSON.stringify({jsonrpc:'2.0',id:randomUUID(),method,params}),signal:AbortSignal.timeout(65000)});const value=await response.json();if(!response.ok||value.error)throw Error(value.error?.message||value.error||'Executor indisponível.');return value.result;}
function route(text){const sections=[...text.matchAll(/^<context>\n([\s\S]*?)\n<\/context>/gm)];if(sections.length!==1)return null;const ctx=sections[0][1],line=ctx.match(/^Channel: (.+)$/m)?.[1],uuid='[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}';const channel=line?.match(new RegExp('(?:^|\\(#)('+uuid+')(?:\\))?$','i'))?.[1];if(!channel)return null;const reply=ctx.match(/--reply-to ([a-f0-9]{64})\b/i)?.[1];return {channel,reply};}
async function publish(destination,text){if(!destination||!process.env.BUZZ_RELAY_URL||!process.env.BUZZ_PRIVATE_KEY)return;const cli=process.env.EQUIPE_BUZZ_CLI||'/Applications/Buzz.app/Contents/MacOS/buzz';const args=['messages','send','--channel',destination.channel,...(destination.reply?['--reply-to',destination.reply]:[]),'--content','-'];await new Promise((resolve,reject)=>{const child=spawn(cli,args,{env:process.env,stdio:['pipe','ignore','pipe']});let error='';child.stderr.on('data',c=>error+=c);child.on('error',reject);child.on('exit',code=>code===0?resolve():reject(Error('Não foi possível publicar a resposta no Buzz.')));child.stdin.end(text);});}
async function handle(req){const p=req.params||{};if(req.method==='initialize')return {protocolVersion:1,agentInfo:{name:'codexbot',title:'Equipe · ChatGPT no Mac',version:'2.0.0'},agentCapabilities:{loadSession:false,promptCapabilities:{image:false,embeddedContext:false}},authMethods:[]};
 if(req.method==='session/new'){const sessionId=randomUUID();sessions.set(sessionId,{});return {sessionId};}
 const s=sessions.get(p.sessionId);if(!s)throw Error('Sessão desconhecida.');
 if(req.method==='session/cancel'){s.cancelled=true;if(s.taskId)await call('CancelTask',{id:s.taskId});return {};}
 if(req.method!=='session/prompt')throw Error('Método ACP não suportado.');if(s.busy)throw Error('Sessão ocupada.');s.busy=true;s.cancelled=false;
 try{const text=(p.prompt||[]).filter(x=>x.type==='text').map(x=>x.text).join('\n');if(!text.trim())throw Error('Envie uma mensagem de texto.');const destination=route(text);const r=await call('SendMessage',{message:{messageId:randomUUID(),role:'ROLE_USER',...(s.contextId?{contextId:s.contextId}:{}),parts:[{text:text.slice(0,31500)+'\n\nResponda no resultado desta tarefa. A ponte cuida de devolver a resposta ao cliente; não use comandos externos para publicar a resposta.'}]},configuration:{returnImmediately:true}});let task=r.task;s.taskId=task.id;s.contextId=task.contextId;
 while(['TASK_STATE_SUBMITTED','TASK_STATE_WORKING'].includes(task.status.state)&&!s.cancelled){await new Promise(r=>setTimeout(r,1000));task=await call('GetTask',{id:s.taskId});}
 const answer=task.artifacts?.flatMap(a=>a.parts.map(p=>p.text||'')).join('\n\n')||task.status.message?.parts?.map(p=>p.text||'').join('\n')||'Tarefa encerrada.';
 output({jsonrpc:'2.0',method:'session/update',params:{sessionId:p.sessionId,update:{sessionUpdate:'agent_message_chunk',content:{type:'text',text:answer}}}});
 if(!s.cancelled)await publish(destination,answer);return {stopReason:s.cancelled?'cancelled':'end_turn'};
 }finally{s.busy=false;}}
readline.createInterface({input:process.stdin}).on('line',line=>{void(async()=>{let req;try{req=JSON.parse(line);const result=await handle(req);if(req.id!==undefined)output({jsonrpc:'2.0',id:req.id,result});}catch(e){if(req?.id!==undefined)output({jsonrpc:'2.0',id:req.id,error:{code:-32603,message:e.message}});}})();});
