const kinds=new Set(['text','input','textarea','choice','table','chart','diagram','html']);
const text=(v,max=2000)=>{if(typeof v!=='string'||v.length>max)throw Error('Texto do card inválido.');return v;};
const list=(v,max)=>{if(!Array.isArray(v)||v.length>max)throw Error('Lista do card inválida.');return v;};
export function validateCard(raw){
 if(!raw||typeof raw!=='object')throw Error('Card inválido.');const ids=new Set();
 const card={title:text(raw.title,160),blocks:list(raw.blocks,30).map(b=>{if(!b||!kinds.has(b.type))throw Error('Tipo de bloco inválido.');const x={type:b.type};
 if(['input','textarea','choice'].includes(b.type)){x.id=text(b.id,64);if(!/^[a-zA-Z][\w-]*$/.test(x.id)||ids.has(x.id))throw Error('Campo duplicado ou inválido.');ids.add(x.id);x.label=text(b.label,300);x.required=b.required===true;if(b.type==='choice'){x.multiple=b.multiple===true;x.options=list(b.options,30).map(o=>({value:text(o.value,120),label:text(o.label,300)}));if(!x.options.length||new Set(x.options.map(o=>o.value)).size!==x.options.length)throw Error('Opções inválidas.');}else{x.value=text(b.value||'',b.type==='input'?2000:32000);x.placeholder=text(b.placeholder||'',300);}}
 else if(b.type==='text')x.text=text(b.text,32000);
 else if(b.type==='html')x.html=text(b.html,100000);
 else if(b.type==='table'){x.columns=list(b.columns,15).map(v=>text(v,200));x.rows=list(b.rows,200).map(r=>list(r,15).map(v=>text(String(v),3000)));}
 else if(b.type==='chart'){x.kind=['bar','line'].includes(b.kind)?b.kind:'bar';x.label=text(b.label||'',300);x.points=list(b.points,60).map(p=>{if(!Number.isFinite(p.value)||Math.abs(p.value)>1e12)throw Error('Valor do gráfico inválido.');return {label:text(p.label,150),value:p.value};});}
 else if(b.type==='diagram'){x.nodes=list(b.nodes,40).map(n=>({id:text(n.id,64),label:text(n.label,300)}));if(new Set(x.nodes.map(n=>n.id)).size!==x.nodes.length)throw Error('Nós duplicados.');x.edges=list(b.edges||[],80).map(e=>{if(!x.nodes.some(n=>n.id===e.from)||!x.nodes.some(n=>n.id===e.to))throw Error('Conexão inválida.');return {from:e.from,to:e.to,label:text(e.label||'',120)};});}return x;
 }),actions:list(raw.actions||[],8).map(a=>({id:text(a.id,64),label:text(a.label,120)}))};
 if(new Set(card.actions.map(a=>a.id)).size!==card.actions.length)throw Error('Ações duplicadas.');return card;
}
export function validateCardResponse(card,input){if(card.response)throw Error('Este card já foi respondido.');if(!card.actions.some(a=>a.id===input.actionId))throw Error('Ação inválida.');const values={};for(const b of card.blocks){if(!['input','textarea','choice'].includes(b.type))continue;const value=input.values?.[b.id];if(b.type==='choice'){const allowed=new Set(b.options.map(o=>o.value));if(b.multiple){if(!Array.isArray(value)||value.length>30||new Set(value).size!==value.length||value.some(v=>!allowed.has(v)))throw Error('Seleção inválida.');if(b.required&&!value.length)throw Error('Preencha os campos obrigatórios.');values[b.id]=value;}else{if(value!==''&&!allowed.has(value))throw Error('Seleção inválida.');if(b.required&&!value)throw Error('Preencha os campos obrigatórios.');values[b.id]=value;}}else{const v=text(value??'',b.type==='input'?2000:32000);if(b.required&&!v.trim())throw Error('Preencha os campos obrigatórios.');values[b.id]=v;}}return {actionId:input.actionId,values};}
export const cardTool={type:'function',name:'team_show_card',description:'Mostra um smart card na conversa: texto Markdown, input, textarea, choice (opções value/label, multiple), table (columns/rows), chart (bar/line, points label/value), diagram (nodes id/label, edges from/to/label), html (HTML/CSS estático isolado, sem scripts/rede). Campos têm id,label,required,value. actions são botões id/label; o clique devolve os valores como nova mensagem ao agente. Não execute a ação até a resposta. Após mostrar uma pergunta, encerre o turno e aguarde. Não substitui team_request_approval para ações externas.',inputSchema:{type:'object',properties:{title:{type:'string'},blocks:{type:'array',items:{type:'object',properties:{type:{type:'string',enum:[...kinds]}},required:['type'],additionalProperties:true}},actions:{type:'array',items:{type:'object',properties:{id:{type:'string'},label:{type:'string'}},required:['id','label'],additionalProperties:false}}},required:['title','blocks'],additionalProperties:false}};
