import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {createFeedback,nextFeedbackReview} from '../feedback.mjs';
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'codexbot-feedback-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));fs.cpSync(new URL('../builtin-skills',import.meta.url),path.join(root,'builtin-skills'),{recursive:true});const agent={id:'general-manager',name:'General Manager',description:'Keep existing rules.',skills:[]},catalog={agents:[agent],skills:[]},state={jobs:[],messages:[{id:'q',role:'user',agentId:agent.id,text:'Explain this'},{id:'a',role:'assistant',agentId:agent.id,text:'An answer.'}]};let calls=0,clock=Date.parse('2026-09-18T12:00:00Z');const manage={skill:s=>{const a={...s,id:'codexbot-feedback-review'};catalog.skills.push(a);return a;},agent:a=>Object.assign(agent,a)};const args={root,state,catalog,manage,enqueue:()=>{calls++;const j={id:'job'+calls,agentId:agent.id,status:'running'};state.jobs.push(j);return j;},now:()=>clock};const f=createFeedback(args);return {f,root,args,agent,state,catalog,calls:()=>calls,time:x=>clock=x,rate:()=>f.rate({messageId:'a',rating:-1,comment:'Please use examples.'}),submit:()=>{const job=state.jobs.at(-1),b=f.review(job,{action:'read'});return f.review(job,{action:'submit',batchId:b.batchId,suggestions:[{agentId:agent.id,feedbackIds:b.feedback.map(x=>x.id),title:'Add examples',rationale:'User asked for examples.',instruction:'Include a concise example when explaining.'}],dismissals:[]});}};}
test('native skill installs once, empty weekly catch-up never invokes AI',t=>{const x=fixture(t);assert.equal(x.catalog.skills.length,1);createFeedback(x.args);assert.equal(x.catalog.skills.length,1);assert.equal(x.f.startReview().reason,'empty');x.time(Date.parse('2026-09-21T15:00:00Z'));x.f.tick();x.f.tick();assert.equal(x.calls(),0);assert.equal(x.f.publicState().nextReviewAt,'2026-09-28T12:00:00.000Z');});
test('feedback persists, deduplicates and review requires its reserved job',t=>{const x=fixture(t);x.rate();x.rate();assert.equal(x.f.publicState().pendingCount,1);assert.equal(createFeedback(x.args).publicState().ratings.a.rating,-1);x.f.startReview();assert.equal(x.f.startReview().reason,'running');assert.equal(x.calls(),1);assert.throws(()=>x.f.review({id:'other'},{action:'read'}));x.submit();assert.equal(x.agent.description,'Keep existing rules.');assert.equal(x.f.publicState().pendingCount,0);assert.equal(x.f.startReview().reason,'empty');const s=x.f.publicState().suggestions[0];x.state.jobs[0].status='completed';x.f.decide({id:s.id,action:'approve'});assert.match(x.agent.description,/Keep existing rules\.\n\nInclude/);x.f.tick();assert.equal(x.agent.description.split('Include').length,2);});
test('automatic incorporation waits for idle; changed instructions require explicit re-review',t=>{const x=fixture(t);x.f.settings({enabled:true,autoApply:true});x.rate();x.f.startReview();x.submit();assert.equal(x.agent.description,'Keep existing rules.');x.agent.description='User edited rules.';x.state.jobs[0].status='completed';x.f.tick();const s=x.f.publicState().suggestions[0];assert(s.conflict);assert.throws(()=>x.f.decide({id:s.id,action:'approve'}));x.f.decide({id:s.id,action:'approve',currentHash:x.f.detail(s.id).currentHash});assert.match(x.agent.description,/^User edited rules\.\n\nInclude/);});
test('rejection leaves instructions untouched and edited feedback is reprocessed',t=>{const x=fixture(t);x.rate();x.f.startReview();x.submit();const s=x.f.publicState().suggestions[0];x.f.decide({id:s.id,action:'reject'});x.f.settings({enabled:true,autoApply:true});assert.equal(x.agent.description,'Keep existing rules.');x.f.rate({messageId:'a',rating:1,comment:'Actually useful'});assert.equal(x.f.publicState().pendingCount,1);});
test('incomplete and stale reviews cannot mark feedback processed',t=>{const x=fixture(t);x.rate();x.f.startReview();const j=x.state.jobs[0],b=x.f.review(j,{action:'read'});assert.throws(()=>x.f.review(j,{action:'submit',batchId:b.batchId,suggestions:[],dismissals:[]}));x.f.rate({messageId:'a',rating:-1,comment:'Updated'});assert.throws(()=>x.submit());assert.equal(x.f.publicState().pendingCount,1);j.status='completed';x.f.tick();assert.equal(x.f.publicState().batch,null);});
test('schedule uses Monday 09:00 São Paulo',()=>assert.equal(nextFeedbackReview(Date.parse('2026-09-20T12:00:00Z')),'2026-09-21T12:00:00.000Z'));
