import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import net from 'node:net';import {spawn} from 'node:child_process';import {setTimeout as delay} from 'node:timers/promises';import {fileURLToPath} from 'node:url';
test('HTTP threads isolate context and every new task starts a fresh model session',async t=>{
 const source=path.dirname(path.dirname(fileURLToPath(import.meta.url))),root=fs.mkdtempSync(path.join(os.tmpdir(),'codexbot-threads-'));let child;t.after(async()=>{if(child){child.kill('SIGTERM');await new Promise(r=>child.once('exit',r));}fs.rmSync(root,{recursive:true,force:true});});
 for(const name of fs.readdirSync(source).filter(n=>n.endsWith('.mjs')))fs.copyFileSync(path.join(source,name),path.join(root,name));for(const name of ['dist','builtin-skills'])fs.cpSync(path.join(source,name),path.join(root,name),{recursive:true});fs.symlinkSync(path.join(source,'node_modules'),path.join(root,'node_modules'),'dir');
 const fake=path.join(root,'fake-codex.cjs');fs.writeFileSync(fake,`#!${process.execPath}\nconst fs=require('fs'),rl=require('readline').createInterface({input:process.stdin});let n=0,retries=0,semantic=0;const out=x=>process.stdout.write(JSON.stringify(x)+'\\n');rl.on('line',line=>{const x=JSON.parse(line);if(!x.id||!x.method)return;fs.appendFileSync(${JSON.stringify(path.join(root,'rpc.jsonl'))},line+'\\n');let result={};if(x.method==='model/list')result={data:['gpt-5.6-luna','gpt-5.6-sol','gpt-6-astra'].map(model=>({model,supportedReasoningEfforts:['low','medium','high','xhigh','max'].map(reasoningEffort=>({reasoningEffort}))}))};if(x.method==='account/read')result={account:{type:'chatgpt',planType:'test'}};if(x.method==='thread/start')result={thread:{id:'t'+(++n)}};if(x.method==='turn/start')result={turn:{id:'turn'+n}};out({id:x.id,result});if(x.method==='turn/start')setTimeout(()=>{const p={threadId:x.params.threadId};const input=x.params.input[0].text.split('Mensagem atual do usuário:').at(-1);if(input.includes('SEMANTIC_FAIL')&&++semantic===1){out({id:1000,method:'item/tool/call',params:{...p,tool:'team_report_outcome',arguments:{reason:'Could not verify synthetic objective',retryable:true}}});setTimeout(()=>out({method:'turn/completed',params:{...p,turn:{status:'completed'}}}),30);return;}const failed=input.includes('ALWAYS_FAIL')||input.includes('SIDE_EFFECT_FAIL')||input.includes('RETRY_RECOVER')&&++retries<3;if(input.includes('SIDE_EFFECT_FAIL'))out({method:'item/started',params:{...p,item:{type:'commandExecution'}}});if(failed){out({method:'turn/completed',params:{...p,turn:{status:'failed',error:{message:'Synthetic execution failure'}}}});return;}out({method:'item/completed',params:{...p,item:{type:'agentMessage',id:'m'+n,text:'Synthetic reply '+n}}});out({method:'turn/completed',params:{...p,turn:{status:'completed'}}});},5);});`,{mode:0o700});
 const listener=net.createServer();await new Promise(r=>listener.listen(0,'127.0.0.1',r));const port=listener.address().port;await new Promise(r=>listener.close(r));child=spawn(process.execPath,[path.join(root,'server.mjs')],{env:{...process.env,EQUIPE_CODEX:fake,CODEXBOT_PORT:String(port)},stdio:'ignore'});
 let token;for(let i=0;i<100;i++){try{token=fs.readFileSync(path.join(root,'.runtime/device-token'),'utf8');await fetch('http://127.0.0.1:'+port+'/');break;}catch{await delay(30);}}
 const api=async(route,body)=>{const r=await fetch('http://127.0.0.1:'+port+'/api/'+route,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const j=await r.json();assert(r.ok,JSON.stringify(j));return j;};
 const finish=async(expected='completed')=>{for(let i=0;i<1000;i++){const s=await api('state');if(s.jobs.length&&!s.jobs.some(j=>['queued','running'].includes(j.status))){assert.equal(s.jobs.at(-1).status,expected,JSON.stringify(s.jobs));return s;}await delay(20);}throw Error('timeout');};
 await api('send',{agentId:'general-manager',text:'MAIN_ONLY_CONTEXT'});let s=await finish();const rootMessage=s.messages.find(m=>m.role==='assistant');const branch=await api('threads',{messageId:rootMessage.id});await api('send',{threadId:branch.id,text:'BRANCH_ONLY_CONTEXT'});s=await finish();await api('send',{threadId:branch.id,text:'Continue this branch'});s=await finish();assert.equal(s.messageThreads.length,1);const calls=fs.readFileSync(path.join(root,'rpc.jsonl'),'utf8').trim().split('\n').map(JSON.parse);const turns=calls.filter(c=>c.method==='turn/start');assert.equal(new Set(turns.map(c=>c.params.threadId)).size,3);assert(!JSON.stringify(turns[1]).includes('MAIN_ONLY_CONTEXT'));assert(JSON.stringify(turns[2]).includes('BRANCH_ONLY_CONTEXT'));assert((await api('messages?conversationId='+encodeURIComponent(branch.id))).messages.every(m=>m.conversationId===branch.id));assert.equal(s.jobs.at(-1).contextUsage.included,2);
 // Separate threads prevent synthetic markers from leaking into later test inputs.
 const b2=await api('threads',{messageId:s.messages.filter(m=>m.role==='assistant').at(-1).id});await api('send',{threadId:b2.id,text:'RETRY_RECOVER'});s=await finish();assert.equal(s.jobs.at(-1).attempts.length,3);assert.deepEqual(s.jobs.at(-1).attempts.map(a=>a.effort),['low','high','max']);assert.equal(s.messages.filter(m=>m.jobId===s.jobs.at(-1).id&&m.role==='user').length,1);assert(s.feedback.pendingCount>0);
 const b3=await api('threads',{messageId:s.messages.filter(m=>m.role==='assistant').at(-1).id});await api('send',{threadId:b3.id,text:'ALWAYS_FAIL'});s=await finish('failed');assert.equal(s.jobs.at(-1).attempts.length,3);assert.equal(s.jobs.at(-1).retryStop,'limit');
 const b4=await api('threads',{messageId:rootMessage.id});await api('send',{threadId:b4.id,text:'SIDE_EFFECT_FAIL'});s=await finish('failed');assert.equal(s.jobs.at(-1).attempts.length,1);assert.equal(s.jobs.at(-1).retryStop,'partial_execution');
 const b5=await api('threads',{messageId:s.messages.filter(m=>m.role==='assistant').at(-1).id});await api('send',{threadId:b5.id,text:'SEMANTIC_FAIL'});s=await finish();assert.equal(s.jobs.at(-1).attempts.length,2);assert.equal(s.jobs.at(-1).attempts[0].status,'failed');
 const failures=JSON.parse(fs.readFileSync(path.join(root,'.runtime/task-failures.json')));assert(failures.entries.some(e=>e.resolved));assert(failures.entries.some(e=>e.terminal));
});
