import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import net from 'node:net';import {spawn} from 'node:child_process';import {setTimeout as delay} from 'node:timers/promises';import {fileURLToPath} from 'node:url';
test('HTTP threads isolate context and every new task starts a fresh model session',async t=>{
 const source=path.dirname(path.dirname(fileURLToPath(import.meta.url))),root=fs.mkdtempSync(path.join(os.tmpdir(),'codexbot-threads-'));let child;t.after(async()=>{if(child){child.kill('SIGTERM');await new Promise(r=>child.once('exit',r));}fs.rmSync(root,{recursive:true,force:true});});
 for(const name of fs.readdirSync(source).filter(n=>n.endsWith('.mjs')))fs.copyFileSync(path.join(source,name),path.join(root,name));for(const name of ['dist','builtin-skills'])fs.cpSync(path.join(source,name),path.join(root,name),{recursive:true});fs.symlinkSync(path.join(source,'node_modules'),path.join(root,'node_modules'),'dir');
 const fake=path.join(root,'fake-codex.cjs');fs.writeFileSync(fake,`#!${process.execPath}\nconst fs=require('fs'),rl=require('readline').createInterface({input:process.stdin});let n=0;const out=x=>process.stdout.write(JSON.stringify(x)+'\\n');rl.on('line',line=>{const x=JSON.parse(line);if(!x.id)return;fs.appendFileSync(${JSON.stringify(path.join(root,'rpc.jsonl'))},line+'\\n');let result={};if(x.method==='account/read')result={account:{type:'chatgpt',planType:'test'}};if(x.method==='thread/start')result={thread:{id:'t'+(++n)}};if(x.method==='turn/start')result={turn:{id:'turn'+n}};out({id:x.id,result});if(x.method==='turn/start')setTimeout(()=>{const p={threadId:x.params.threadId};out({method:'item/completed',params:{...p,item:{type:'agentMessage',id:'m'+n,text:'Synthetic reply '+n}}});out({method:'turn/completed',params:{...p,turn:{status:'completed'}}});},5);});`,{mode:0o700});
 const listener=net.createServer();await new Promise(r=>listener.listen(0,'127.0.0.1',r));const port=listener.address().port;await new Promise(r=>listener.close(r));child=spawn(process.execPath,[path.join(root,'server.mjs')],{env:{...process.env,EQUIPE_CODEX:fake,CODEXBOT_PORT:String(port)},stdio:'ignore'});
 let token;for(let i=0;i<100;i++){try{token=fs.readFileSync(path.join(root,'.runtime/device-token'),'utf8');await fetch('http://127.0.0.1:'+port+'/');break;}catch{await delay(30);}}
 const api=async(route,body)=>{const r=await fetch('http://127.0.0.1:'+port+'/api/'+route,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const j=await r.json();assert(r.ok,JSON.stringify(j));return j;};
 const finish=async()=>{for(let i=0;i<100;i++){const s=await api('state');if(s.jobs.length&&!s.jobs.some(j=>['queued','running'].includes(j.status))){assert(s.jobs.every(j=>j.status==='completed'),JSON.stringify(s.jobs));return s;}await delay(20);}throw Error('timeout');};
 await api('send',{agentId:'general-manager',text:'MAIN_ONLY_CONTEXT'});let s=await finish();const rootMessage=s.messages.find(m=>m.role==='assistant');const branch=await api('threads',{messageId:rootMessage.id});await api('send',{threadId:branch.id,text:'BRANCH_ONLY_CONTEXT'});s=await finish();await api('send',{threadId:branch.id,text:'Continue this branch'});s=await finish();assert.equal(s.messageThreads.length,1);const calls=fs.readFileSync(path.join(root,'rpc.jsonl'),'utf8').trim().split('\n').map(JSON.parse);const turns=calls.filter(c=>c.method==='turn/start');assert.equal(new Set(turns.map(c=>c.params.threadId)).size,3);assert(!JSON.stringify(turns[1]).includes('MAIN_ONLY_CONTEXT'));assert(JSON.stringify(turns[2]).includes('BRANCH_ONLY_CONTEXT'));assert((await api('messages?conversationId='+encodeURIComponent(branch.id))).messages.every(m=>m.conversationId===branch.id));assert.equal(s.jobs.at(-1).contextUsage.included,2);
});
